# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Actualizaciones para npm
  - package-ecosystem: "npm"
    directory: "/" # Ubicación del archivo package.json
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"

  # Actualizaciones para Python (pip)
  - package-ecosystem: "pip"
    directory: "/" # Ubicación del archivo requirements.txt
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
