#!/bin/bash

# Activar el entorno virtual
source venv/bin/activate

# Exportar variables de entorno necesarias
export FLASK_APP=src/backend/app.py
export FLASK_ENV=development

# Iniciar el servidor de desarrollo de Flask
flask run --host=0.0.0.0 --port=8080
